POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Captain Morgan",
    "trash": "This is useless data",
    "number": "111-111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "trash": "This is useless data"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Captain Ward"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123"
}

###

PUT http://localhost:3001/api/persons/65b1aea21e3cc8f16b419eb0
Content-Type: application/json

{
    "name": "Captain Hook",
    "number": 321
}

###
PUT http://localhost:3001/api/persons/65b1aea21e3cc8f16b419eb0
Content-Type: application/json

{
    "name": "Captain Hook"
}

###
PUT http://localhost:3001/api/persons/65b1aea21e3cc8f16b419eb0
Content-Type: application/json

{
    "number": 321
}

###
GET http://localhost:3001/api/persons
