POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1YzNmNzA3YWIwOGNmNjI1ZmFkYjRkZCIsImlhdCI6MTcwNzM0MzU2NH0.aT1zK04nadAnZyRX-yCyLqWxgF-3c6bfPeale6LygDA

{
  "title": "maybe",
  "author": "it's not",
  "url": "awkward!",
  "likes": 96
}

###
GET http://localhost:3003/api/blogs/65c3f8eed5d0a11cfab600c6

###
DELETE http://localhost:3003/api/blogs/65c401d69d03e04295ac5662
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1YzNmNzA3YWIwOGNmNjI1ZmFkYjRkZCIsImlhdCI6MTcwNzM0MzU2NH0.aT1zK04nadAnZyRX-yCyLqWxgF-3c6bfPeale6LygDA

###
GET http://localhost:3003/api/blogs